leftnav:
- identifier: external--236184328-1684163112963
  name: Introductory Programming Courses
  url: https://ocw.mit.edu/collections/introductory-programming/
  weight: 10
- identifier: external-1372500589-1685042995792
  name: Archived D-Space Course
  url: https://dspace.mit.edu/handle/1721.1/150580
  weight: 20
